plataforma_web/blueprints/materias/views.py
"""
Materias, vistas
"""

import json
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_message, safe_string

from plataforma_web.blueprints.bitacoras.models import Bitacora
from plataforma_web.blueprints.materias.models import Materia
from plataforma_web.blueprints.materias.forms import MateriaForm
from plataforma_web.blueprints.modulos.models import Modulo
from plataforma_web.blueprints.permisos.models import Permiso
from plataforma_web.blueprints.usuarios.decorators import permission_required

materias = Blueprint("materias", __name__, template_folder="templates")

MODULO = "MATERIAS"


@materias.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@materias.route("/materias/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Materias"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Materia.query
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    registros = consulta.order_by(Materia.nombre).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "nombre": resultado.nombre,
                    "url": url_for("materias.detail", materia_id=resultado.id),
                },
                "descripcion": resultado.descripcion,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@materias.route("/materias/select_json", methods=["GET", "POST"])
def select_json():
    """Select JSON para materias"""
    # Consultar
    consulta = Materia.query.filter_by(estatus="A").order_by(Materia.nombre)
    # Elaborar datos para Select
    data = []
    for resultado in consulta.all():
        data.append(
            {
                "id": resultado.id,
                "nombre": resultado.nombre,
            }
        )
    # Entregar JSON
    return json.dumps(data)


@materias.route("/materias")
def list_active():
    """Listado de Materias activos"""
    return render_template(
        "materias/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Materias",
        estatus="A",
    )


@materias.route("/materias/inactivos")
@permission_required(MODULO, Permiso.MODIFICAR)
def list_inactive():
    """Listado de Materias inactivos"""
    return render_template(
        "materias/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Materias inactivos",
        estatus="B",
    )


@materias.route("/materias/<int:materia_id>")
def detail(materia_id):
    """Detalle de una Materia"""
    materia = Materia.query.get_or_404(materia_id)
    return render_template("materias/detail.jinja2", materia=materia)


@materias.route("/materias/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nueva Materia"""
    form = MateriaForm()
    if form.validate_on_submit():
        es_valido = True
        # Validar que el nombre no se repita
        nombre = safe_string(form.nombre.data, save_enie=True)
        if Materia.query.filter_by(nombre=nombre).first():
            flash("La nombre ya está en uso. Debe de ser único.", "warning")
            es_valido = False
        # Validar la descripcion
        descripcion = safe_string(form.descripcion.data, save_enie=True, to_uppercase=False, max_len=1024)
        if descripcion == "":
            flash("La descripción no es válida.", "warning")
            es_valido = False
        # Si es valido crear
        if es_valido:
            materia = Materia(nombre=nombre, descripcion=descripcion)
            materia.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Nueva materia {materia.nombre}"),
                url=url_for("materias.detail", materia_id=materia.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    return render_template("materias/new.jinja2", form=form)


@materias.route("/materias/edicion/<int:materia_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(materia_id):
    """Editar Materia"""
    materia = Materia.query.get_or_404(materia_id)
    form = MateriaForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia el nombre verificar que no este en uso
        nombre = safe_string(form.nombre.data, save_enie=True)
        if materia.nombre != nombre:
            materia_existente = Materia.query.filter_by(nombre=nombre).first()
            if materia_existente and materia_existente.id != materia_id:
                es_valido = False
                flash("El nombre ya está en uso. Debe de ser único.", "warning")
        # Validar la descripcion
        descripcion = safe_string(form.descripcion.data, save_enie=True, to_uppercase=False, max_len=1024)
        if descripcion == "":
            flash("La descripción no es válida.", "warning")
            es_valido = False
        # Si es valido actualizar
        if es_valido:
            materia.nombre = nombre
            materia.descripcion = descripcion
            materia.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editada materia {materia.nombre}"),
                url=url_for("materias.detail", materia_id=materia.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.nombre.data = materia.nombre
    form.descripcion.data = materia.descripcion
    return render_template("materias/edit.jinja2", form=form, materia=materia)


@materias.route("/materias/eliminar/<int:materia_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def delete(materia_id):
    """Eliminar Materia"""
    materia = Materia.query.get_or_404(materia_id)
    if materia.estatus == "A":
        materia.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminada materia {materia.nombre}"),
            url=url_for("materias.detail", materia_id=materia.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("materias.detail", materia_id=materia.id))


@materias.route("/materias/recuperar/<int:materia_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def recover(materia_id):
    """Recuperar Materia"""
    materia = Materia.query.get_or_404(materia_id)
    if materia.estatus == "B":
        materia.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperada materia {materia.nombre}"),
            url=url_for("materias.detail", materia_id=materia.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("materias.detail", materia_id=materia.id))

plataforma_web/blueprints/materias/templates/materias/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Materia{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Materia ' + materia.nombre) %}
        {{ topbar.button_previous('Materias', url_for('materias.list_active')) }}
        {% if current_user.can_edit('MATERIAS') %}
            {{ topbar.button_edit('Editar', url_for('materias.edit', materia_id=materia.id)) }}
            {% if materia.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('materias.delete', materia_id=materia.id)) }}{% endif %}
            {% if materia.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('materias.recover', materia_id=materia.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=materia.estatus) %}
        {{ detail.label_value('Descripción', materia.descripcion) }}
    {% endcall %}
    {% if current_user.can_view('AUTORIDADES') %}
        {% call detail.card(title='Autoridades') %}
            <table id="autoridades_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Clave</th>
                        <th>Descripción corta</th>
                        <th>Órgano Jurisdiccional</th>
                        <th>Distrito</th>
                        <th>Sede</th>
                        <th>Extinto</th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
    {% if current_user.can_view('MATERIAS TIPOS JUICIOS') %}
        {% call detail.card(title='Tipos de Juicios') %}
            <table id="materias_tipos_juicios_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Tipos de Juicios</th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_edit('MATERIAS') %}
        {% if materia.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + materia.nombre + '?') }}{% endif %}
        {% if materia.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + materia.nombre + '?') }}{% endif %}
    {% endif %}
    {{ detail.config_datatable() }}
    {% if current_user.can_view('AUTORIDADES') %}
        <script>
            configDataTable['ajax']['url'] = '/autoridades/datatable_json';
            configDataTable['ajax']['data'] = { 'estatus': "A", 'materia_id': {{ materia.id}} };
            configDataTable['columns'] = [
                { data: "detalle" },
                { data: "descripcion_corta" },
                { data: "organo_jurisdiccional" },
                { data: "distrito" },
                { data: "sede" },
                { data: "es_extinto" }
            ];
            configDataTable['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.clave + '</a>';
                    }
                },
                {
                    targets: 3, // distrito
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.url == '') {
                            return data.nombre_corto;
                        }
                        return '<a href="' + data.url + '">' + data.nombre_corto + '</a>';
                    }
                }
            ];
            configDataTable['rowCallback'] = function (row, data) {
                if (data.es_extinto == 'EXTINTO') {
                    $(row).css("background-color", "#c0c0c0");
                }
            };
            $('#autoridades_datatable').DataTable(configDataTable);
        </script>
    {% endif %}
    {% if current_user.can_view('MATERIAS TIPOS JUICIOS') %}
        <script>
            configDataTable['ajax']['url'] = '/materias_tipos_juicios/datatable_json';
            configDataTable['ajax']['data'] = { 'estatus': "A", 'materia_id': {{ materia.id}} };
            configDataTable['columns'] = [
                { data: "detalle" }
            ];
            configDataTable['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.descripcion + '</a>';
                    }
                }
            ];
            $('#materias_tipos_juicios_datatable').DataTable(configDataTable);
        </script>
    {% endif %}
{% endblock %}

plataforma_web/blueprints/materias/templates/materias/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Materia{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar ' + materia.nombre) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'materia_id': materia.id} %}
        {% call f.form_tag('materias.edit', fid='materia_form', **form_kwargs) %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.descripcion) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

plataforma_web/blueprints/materias/templates/materias/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Materias{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('AUTORIDADES') %}
            {{ topbar.button('Autoridades', url_for('autoridades.list_active'), 'mdi:scale-balance') }}
        {% endif %}
        {% if current_user.can_view('DISTRITOS') %}
            {{ topbar.button_districts('Distritos', url_for('distritos.list_active')) }}
        {% endif %}
        {% if current_user.can_admin('MATERIAS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivas', url_for('materias.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activas', url_for('materias.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('MATERIAS') %}
            {{ topbar.button_new('Nueva Materia', url_for('materias.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <table id="materias_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Materia</th>
                    <th>Descripción</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ list.config_datatable() }}
    <script>
        configDataTable['ajax']['url'] = '/materias/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: "detalle" },
            { data: "descripcion" }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.nombre + '</a>';
                }
            },
            {
                targets: 1, // descripcion
                data: null,
                render: function(data, type, row, meta) {
                    return data.length > 128 ? data.substr(0, 128) + '…' : data;
                }
            }
        ];
        $('#materias_datatable').DataTable(configDataTable);
    </script>
{% endblock %}

plataforma_web/blueprints/materias/templates/materias/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nueva Materia{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nueva Materia') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('materias.new', fid='materia_form') %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.descripcion) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}