plataforma_web/blueprints/abogados/views.py
"""
Abogados, vistas
"""
import json
from flask import Blueprint, flash, redirect, request, render_template, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_string, safe_message
from plataforma_web.blueprints.usuarios.decorators import permission_required

from plataforma_web.blueprints.abogados.models import Abogado
from plataforma_web.blueprints.abogados.forms import AbogadoForm, AbogadoSearchForm
from plataforma_web.blueprints.bitacoras.models import Bitacora
from plataforma_web.blueprints.modulos.models import Modulo
from plataforma_web.blueprints.permisos.models import Permiso

abogados = Blueprint("abogados", __name__, template_folder="templates")

MODULO = "ABOGADOS"


@abogados.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@abogados.route("/abogados/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de abogados"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Abogado.query
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "fecha_desde" in request.form:
        consulta = consulta.filter(Abogado.fecha >= request.form["fecha_desde"])
    if "fecha_hasta" in request.form:
        consulta = consulta.filter(Abogado.fecha <= request.form["fecha_hasta"])
    if "numero" in request.form:
        consulta = consulta.filter_by(numero=safe_string(request.form["numero"]))
    if "libro" in request.form:
        consulta = consulta.filter_by(libro=safe_string(request.form["libro"]))
    if "nombre" in request.form:
        consulta = consulta.filter(Abogado.nombre.contains(safe_string(request.form["nombre"])))
    registros = consulta.order_by(Abogado.id.desc()).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for abogado in registros:
        data.append(
            {
                "detalle": {
                    "nombre": abogado.nombre,
                    "url": url_for("abogados.detail", abogado_id=abogado.id),
                },
                "fecha": abogado.fecha.strftime("%Y-%m-%d 00:00:00"),
                "numero": abogado.numero,
                "libro": abogado.libro,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@abogados.route("/abogados")
def list_active():
    """Listado de Abogados activos"""
    return render_template(
        "abogados/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Abogados registrados",
        estatus="A",
    )


@abogados.route("/abogados/inactivos")
@permission_required(MODULO, Permiso.MODIFICAR)
def list_inactive():
    """Listado de Abogados inactivos"""
    return render_template(
        "abogados/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Abogados registrados inactivos",
        estatus="B",
    )


@abogados.route("/abogados/buscar", methods=["GET", "POST"])
def search():
    """Buscar Abogados"""
    form_search = AbogadoSearchForm()
    if form_search.validate_on_submit():
        busqueda = {"estatus": "A"}
        titulos = []
        if form_search.fecha_desde.data:
            busqueda["fecha_desde"] = form_search.fecha_desde.data.strftime("%Y-%m-%d")
            titulos.append("fecha desde " + busqueda["fecha_desde"])
        if form_search.fecha_hasta.data:
            busqueda["fecha_hasta"] = form_search.fecha_hasta.data.strftime("%Y-%m-%d")
            titulos.append("fecha hasta " + busqueda["fecha_hasta"])
        if form_search.numero.data:
            numero = safe_string(form_search.numero.data)
            if numero != "":
                busqueda["numero"] = numero
                titulos.append("número " + numero)
        if form_search.libro.data:
            libro = safe_string(form_search.libro.data)
            if libro != "":
                busqueda["libro"] = libro
                titulos.append("libro " + libro)
        if form_search.nombre.data:
            nombre = safe_string(form_search.nombre.data, save_enie=True)
            if nombre != "":
                busqueda["nombre"] = nombre
                titulos.append("nombre " + nombre)
        return render_template(
            "abogados/list.jinja2",
            filtros=json.dumps(busqueda),
            titulo="Abogados registrados con " + ", ".join(titulos),
            estatus="A",
        )
    return render_template("abogados/search.jinja2", form=form_search)


@abogados.route("/abogados/<int:abogado_id>")
def detail(abogado_id):
    """Detalle de un Abogado"""
    abogado = Abogado.query.get_or_404(abogado_id)
    return render_template("abogados/detail.jinja2", abogado=abogado)


@abogados.route("/abogados/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Abogado"""
    form = AbogadoForm()
    if form.validate_on_submit():
        abogado = Abogado(
            numero=safe_string(form.numero.data),
            nombre=safe_string(form.nombre.data, save_enie=True),
            libro=safe_string(form.libro.data),
            fecha=form.fecha.data,
        )
        abogado.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Nuevo abogado registrado {abogado.nombre} con número {abogado.numero}"),
            url=url_for("abogados.detail", abogado_id=abogado.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return render_template("abogados/new.jinja2", form=form)


@abogados.route("/abogados/edicion/<int:abogado_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(abogado_id):
    """Editar Abogado"""
    abogado = Abogado.query.get_or_404(abogado_id)
    form = AbogadoForm()
    if form.validate_on_submit():
        abogado.numero = safe_string(form.numero.data)
        abogado.nombre = safe_string(form.nombre.data, save_enie=True)
        abogado.libro = safe_string(form.libro.data)
        abogado.fecha = form.fecha.data
        abogado.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Editado abogado registrado {abogado.nombre}"),
            url=url_for("abogados.detail", abogado_id=abogado.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    form.numero.data = abogado.numero
    form.nombre.data = abogado.nombre
    form.libro.data = abogado.libro
    form.fecha.data = abogado.fecha
    return render_template("abogados/edit.jinja2", form=form, abogado=abogado)


@abogados.route("/abogados/eliminar/<int:abogado_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def delete(abogado_id):
    """Eliminar Abogado"""
    abogado = Abogado.query.get_or_404(abogado_id)
    if abogado.estatus == "A":
        abogado.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado abogado registrado {abogado.nombre}"),
            url=url_for("abogados.detail", abogado_id=abogado.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("abogados.detail", abogado_id=abogado_id))


@abogados.route("/abogados/recuperar/<int:abogado_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def recover(abogado_id):
    """Recuperar Abogado"""
    abogado = Abogado.query.get_or_404(abogado_id)
    if abogado.estatus == "B":
        abogado.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado abogado registrado {abogado.nombre}"),
            url=url_for("abogados.detail", abogado_id=abogado.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("abogados.detail", abogado_id=abogado_id))

plataforma_web/blueprints/abogados/templates/abogados/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Abogado registrado{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Abogado registrado') %}
        {{ topbar.button_previous('Abogados registrados', url_for('abogados.list_active')) }}
        {% if current_user.can_edit("ABOGADOS") %}
            {{ topbar.button_edit('Editar', url_for('abogados.edit', abogado_id=abogado.id)) }}
            {% if abogado.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('abogados.delete', abogado_id=abogado.id)) }}{% endif %}
            {% if abogado.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('abogados.recover', abogado_id=abogado.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=abogado.estatus) %}
        {{ detail.label_value_big('Nombre', abogado.nombre) }}
        {{ detail.label_value('Fecha', moment(abogado.fecha, local=True).format("DD MMM YYYY")) }}
        {{ detail.label_value('Número', abogado.numero) }}
        {{ detail.label_value('Libro', abogado.libro) }}
        {{ detail.label_value('Creado', moment(abogado.creado).format('llll')) }}
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_edit("ABOGADOS") %}
        {% if abogado.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + abogado.nombre + '?') }}{% endif %}
        {% if abogado.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + abogado.nombre + '?') }}{% endif %}
    {% endif %}
    {{ detail.moment_js(moment) }}
{% endblock %}

plataforma_web/blueprints/abogados/templates/abogados/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Abogado registrado{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar ' + abogado.nombre) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'abogado_id': abogado.id} %}
        {% call f.form_tag('abogados.edit', fid='abogado_form', **form_kwargs) %}
            {% call f.form_group(form.fecha) %}{% endcall %}
            {% call f.form_group(form.numero) %}{% endcall %}
            {% call f.form_group(form.libro) %}{% endcall %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

plataforma_web/blueprints/abogados/templates/abogados/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Abogados registrados{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_edit("ABOGADOS") %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('abogados.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('abogados.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert("ABOGADOS") %}
            {{ topbar.button_new('Nuevo Abogado', url_for('abogados.new')) }}
        {% endif %}
        {{ topbar.button_search('Buscar', url_for('abogados.search')) }}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <table id="abogados_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Números</th>
                    <th>Fechas</th>
                    <th>Libros</th>
                    <th>Nombres</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ list.config_datatable() }}
    <script>
        configDataTable['ajax']['url'] = '/abogados/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: "numero" },
            { data: "fecha" },
            { data: "libro" },
            { data: "detalle" }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 1,
                type: "date",
                render: function (data, type, row) {
                    return moment(data).format("DD MMM YYYY");
                }
            },
            {
                targets: 3,
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.nombre + '</a>';
                }
            }
        ];
        $('#abogados_datatable').DataTable(configDataTable);
    </script>
{% endblock %}

plataforma_web/blueprints/abogados/templates/abogados/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Abogado registrado{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Abogado registrado') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('abogados.new', fid='abogados_form') %}
            {% call f.form_group(form.fecha) %}{% endcall %}
            {% call f.form_group(form.numero) %}{% endcall %}
            {% call f.form_group(form.libro) %}{% endcall %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

plataforma_web/blueprints/abogados/templates/abogados/search.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Buscar Abogados registrados{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Buscar Abogados registrados') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('abogados.search', fid='abogados_search_form') %}
            {% call f.form_group(form.fecha_desde) %}{% endcall %}
            {% call f.form_group(form.fecha_hasta) %}{% endcall %}
            {% call f.form_group(form.numero) %}{% endcall %}
            {% call f.form_group(form.libro) %}{% endcall %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.buscar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}