plataforma_web/blueprints/roles/models.py
"""
Roles, modelos
"""
from plataforma_web.extensions import db
from lib.universal_mixin import UniversalMixin


class Rol(db.Model, UniversalMixin):
    """Rol"""

    # Nombre de la tabla
    __tablename__ = "roles"

    # Clave primaria
    id = db.Column(db.Integer, primary_key=True)

    # Columnas
    nombre = db.Column(db.String(256), unique=True, nullable=False)

    # Hijos
    permisos = db.relationship("Permiso", back_populates="rol")
    usuarios_roles = db.relationship("UsuarioRol", back_populates="rol")
    soportes_categorias_roles = db.relationship("SoporteCategoria", back_populates="rol")

    def __repr__(self):
        """Representación"""
        return f"<Rol {self.nombre}>"

plataforma_web/blueprints/roles/forms.py
"""
Roles, formularios
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class RolForm(FlaskForm):
    """Formulario Rol"""

    nombre = StringField("Nombre", validators=[DataRequired(), Length(max=256)])
    guardar = SubmitField("Guardar")

plataforma_web/blueprints/roles/views.py
"""
Roles, vistas
"""

import json
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_message, safe_string
from plataforma_web.blueprints.usuarios.decorators import permission_required

from plataforma_web.blueprints.bitacoras.models import Bitacora
from plataforma_web.blueprints.modulos.models import Modulo
from plataforma_web.blueprints.permisos.models import Permiso
from plataforma_web.blueprints.roles.models import Rol
from plataforma_web.blueprints.roles.forms import RolForm

MODULO = "ROLES"

roles = Blueprint("roles", __name__, template_folder="templates")


@roles.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@roles.route("/roles/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Roles"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Rol.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "nombre" in request.form:
        nombre = safe_string(request.form["nombre"], save_enie=True)
        if nombre != "":
            consulta = consulta.filter(Rol.nombre.contains(nombre))
    # Ordenar y paginar
    registros = consulta.order_by(Rol.nombre).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "nombre": resultado.nombre,
                    "url": url_for("roles.detail", rol_id=resultado.id),
                },
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@roles.route("/roles")
def list_active():
    """Listado de Roles activos"""
    return render_template(
        "roles/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Roles",
        estatus="A",
    )


@roles.route("/roles/inactivos")
@permission_required(MODULO, Permiso.MODIFICAR)
def list_inactive():
    """Listado de Roles inactivos"""
    return render_template(
        "roles/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Roles inactivos",
        estatus="B",
    )


@roles.route("/roles/<int:rol_id>")
def detail(rol_id):
    """Detalle de un rol"""
    rol = Rol.query.get_or_404(rol_id)
    return render_template("roles/detail.jinja2", rol=rol)


@roles.route("/roles/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Rol"""
    form = RolForm()
    if form.validate_on_submit():
        # Validar que el nombre no se repita
        nombre = safe_string(form.nombre.data, save_enie=True)
        if Rol.query.filter_by(nombre=nombre).first():
            flash("La nombre ya está en uso. Debe de ser único.", "warning")
        else:
            rol = Rol(nombre=nombre)
            rol.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Nuevo rol {rol.nombre}"),
                url=url_for("roles.detail", rol_id=rol.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    return render_template("roles/new.jinja2", form=form)


@roles.route("/roles/edicion/<int:rol_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(rol_id):
    """Editar Rol"""
    rol = Rol.query.get_or_404(rol_id)
    form = RolForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia el nombre verificar que no este en uso
        nombre = safe_string(form.nombre.data, save_enie=True)
        if rol.nombre != nombre:
            rol_existente = Rol.query.filter_by(nombre=nombre).first()
            if rol_existente and rol_existente.id != rol.id:
                es_valido = False
                flash("El nombre ya está en uso. Debe de ser único.", "warning")
        # Si es valido actualizar
        if es_valido:
            rol.nombre = nombre
            rol.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editado rol {rol.nombre}"),
                url=url_for("roles.detail", rol_id=rol.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.nombre.data = rol.nombre
    return render_template("roles/edit.jinja2", form=form, rol=rol)


@roles.route("/rol/eliminar/<int:rol_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def delete(rol_id):
    """Eliminar Rol"""
    rol = Rol.query.get_or_404(rol_id)
    if rol.estatus == "A":
        rol.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado rol {rol.nombre}"),
            url=url_for("roles.detail", rol_id=rol.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("rol.detail", rol_id=rol.id))


@roles.route("/roles/recuperar/<int:rol_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def recover(rol_id):
    """Recuperar Rol"""
    rol = Rol.query.get_or_404(rol_id)
    if rol.estatus == "B":
        rol.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado rol {rol.nombre}"),
            url=url_for("roles.detail", rol_id=rol.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("roles.detail", rol_id=rol.id))

plataforma_web/blueprints/roles/templates/roles/detail.html
{% extends 'layouts/app.html' %}
{% import 'macros/detail.html' as detail with context %}

{% block title %}Rol{% endblock %}

{% block content %}
    {{ detail.page_breadcrumb('Rol') }}
    <div class="container-fluid">
        {% call detail.card() %}
            {{ detail.label_value_big('Rol', rol.nombre) }}
        {% endcall %}
        {% if usuarios %}
            {% call detail.card('Usuarios') %}
            <table id="usuarios_datatable" class="table">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>e-mail</th>
                    </tr>
                </thead>
                <tbody>
                    {% for usuario in usuarios: %}
                    <tr>
                        <td><a href="{{ url_for('usuarios.detail', usuario_id=usuario.id) }}">{{ usuario.nombre }}</a></td>
                        <td>{{ usuario.email }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endcall %}
        {% endif %}
    </div>
{% endblock %}

{% block custom_javascript %}
    <script>
        $('#usuarios_datatable').DataTable({ "searching": false, "info":false, "paging": false });
    </script>
{% endblock %}

plataforma_web/blueprints/roles/templates/roles/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Rol{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Rol ' + rol.nombre) %}
        {{ topbar.button_previous('Roles', url_for('roles.list_active')) }}
        {% if current_user.can_edit('ROLES') %}
            {{ topbar.button_edit('Editar', url_for('roles.edit', rol_id=rol.id)) }}
            {% if rol.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('roles.delete', rol_id=rol.id)) }}{% endif %}
            {% if rol.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('roles.recover', rol_id=rol.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% if current_user.can_view('PERMISOS') %}
        {% call detail.card('Permisos') %}
            <!-- Filtros permisos -->
            <div class="row">
                <div class="col">
                    <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosPermisos.buscar(); return false;">
                        <div class="col-3">
                            <div class="form-floating">
                                <input id="filtroPermisoNombre" type="text" class="form-control" aria-label="Nombre" style="text-transform: uppercase;">
                                <label for="filtroPermisoNombre">Nombre</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input id="filtroPermisoModuloNombre" type="text" class="form-control" aria-label="Módulo" style="text-transform: uppercase;">
                                <label for="filtroPermisoModuloNombre">Módulo</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <select id="filtroPermisoNivel" class="form-select" aria-label="Nivel">
                                <option selected value="">Todos los niveles</option>
                                <option value="1">VER</option>
                                <option value="2">VER y MODIFICAR</option>
                                <option value="3">VER, MODIFICAR y CREAR</option>
                                <option value="4">ADMINISTRAR</option>
                            </select>
                        </div>
                        <div class="col-3 text-end">
                            <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosPermisos.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                            <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosPermisos.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Datatable permisos -->
            <table id="permisos_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Módulo</th>
                        <th>Nivel</th>
                    </tr>
                </thead>
            </table>
            {% if current_user.can_insert('PERMISOS') %}
            <a href="{{ url_for('permisos.new_with_rol', rol_id=rol.id) }}" class="btn btn-primary">Agregar</a>
            {% endif %}
        {% endcall %}
    {% endif %}
    {% if current_user.can_view('USUARIOS ROLES') %}
        {% call detail.card('Usuarios') %}
            <!-- Filtros usuarios-roles -->
            <div class="row">
                <div class="col">
                    <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosUsuarios.buscar(); return false;">
                        <div class="col-4">
                            <div class="form-floating">
                                <input id="filtroEMail" type="text" class="form-control" aria-label="e-mail">
                                <label for="filtroEMail">e-mail</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input id="filtroNombres" type="text" class="form-control" aria-label="Nombres" style="text-transform: uppercase;">
                                <label for="filtroNombres">Nombres</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating">
                                <input id="filtroApellidoPrimero" type="text" class="form-control" aria-label="Apellido primero" style="text-transform: uppercase;">
                                <label for="filtroApellidoPrimero">Apellido primero</label>
                            </div>
                        </div>
                        <div class="col-2 text-end">
                            <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosUsuarios.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                            <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosUsuarios.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Datatable usuarios-roles -->
            <table id="usuarios_roles_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Correo electrónico</th>
                        <th>Nombre completo</th>
                        <th>Puesto</th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_edit('ROLES') %}
        {% if rol.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + rol.nombre + '?') }}{% endif %}
        {% if rol.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + rol.nombre + '?') }}{% endif %}
    {% endif %}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    <script>
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
    </script>
    {% if current_user.can_view('PERMISOS') %}
        <script>
            // DataTable permisos
            let configDTPermisos = constructorDataTable.config();
            configDTPermisos['ajax']['url'] = '/permisos/datatable_json';
            configDTPermisos['ajax']['data'] = { 'estatus': "A", 'rol_id': {{ rol.id}} };
            configDTPermisos['columns'] = [
                { data: "detalle" },
                { data: "modulo" },
                { data: "nivel" }
            ];
            configDTPermisos['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.nombre + '</a>';
                    }
                },
                {
                    targets: 1, // modulo
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.url == '') {
                            return data.nombre;
                        } else {
                            return '<a href="' + data.url + '">' + data.nombre + '</a>';
                        }
                    }
                }
            ];
            // Filtros permisos
            const filtrosPermisos = new FiltrosDataTable('#permisos_datatable', configDTPermisos);
            filtrosPermisos.agregarInput('filtroPermisoNombre', 'nombre');
            filtrosPermisos.agregarInput('filtroPermisoModuloNombre', 'modulo_nombre');
            filtrosPermisos.agregarInput('filtroPermisoNivel', 'nivel');
            filtrosPermisos.precargar();
        </script>
    {% endif %}
    {% if current_user.can_view('USUARIOS ROLES') %}
        <script>
            // DataTable usuarios-roles
            let configDTUsuarios = constructorDataTable.config();
            configDTUsuarios['ajax']['url'] = '/usuarios_roles/datatable_json';
            configDTUsuarios['ajax']['data'] = { 'estatus': "A", 'rol_id': {{ rol.id}} };
            configDTUsuarios['columns'] = [
                { data: "detalle" },
                { data: "usuario" },
                { data: "usuario_nombre" },
                { data: "usuario_puesto" }
            ];
            configDTUsuarios['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.id + '</a>';
                    }
                },
                {
                    targets: 1, // usuario
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.url == '') {
                            return data.email;
                        } else {
                            return '<a href="' + data.url + '">' + data.email + '</a>';
                        }
                    }
                },
                {
                    targets: [2, 3], // usuario_nombre, usuario_puesto
                    data: null,
                    render: function(data, type, row, meta) {
                        return (data.length > 32 ? data.substr(0, 32) + '…' : data);
                    }
                }
            ];
            // Filtros usuarios-roles
            const filtrosUsuarios = new FiltrosDataTable('#usuarios_roles_datatable', configDTUsuarios);
            filtrosUsuarios.agregarInput('filtroEMail', 'email');
            filtrosUsuarios.agregarInput('filtroNombres', 'nombres');
            filtrosUsuarios.agregarInput('filtroApellidoPrimero', 'apellido_paterno');
            filtrosUsuarios.precargar();
        </script>
    {% endif %}
    {{ detail.moment_js(moment) }}
{% endblock %}

plataforma_web/blueprints/roles/templates/roles/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Rol{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar rol ' + rol.nombre) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'rol_id': rol.id} %}
        {% call f.form_tag('roles.edit', fid='rol_form', **form_kwargs) %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

plataforma_web/blueprints/roles/templates/roles/list.html
{% extends 'layouts/app.html' %}
{% import 'macros/list.html' as list with context %}

{% block title %}Roles{% endblock %}

{% block content %}
    {{ list.page_breadcrumb('Roles') }}
    <div class="container-fluid">
        {% call list.card() %}
            <table id="roles_datatable" class="table">
                <thead>
                    <tr>
                        <th>Rol</th>
                    </tr>
                </thead>
                <tbody>
                    {% for rol in roles %}
                    <tr>
                        <td><a href="{{ url_for('roles.detail', rol_id=rol.id) }}">{{ rol.nombre }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endcall %}
    </div>
{% endblock %}

{% block custom_javascript %}
    <script>
        $('#roles_datatable').DataTable();
    </script>
{% endblock %}

plataforma_web/blueprints/roles/templates/roles/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Roles{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('MODULOS') %}
            {{ topbar.button('Módulos', url_for('modulos.list_active'), 'mdi:toy-brick') }}
        {% endif %}
        {% if current_user.can_view('PERMISOS') %}
            {{ topbar.button('Permisos', url_for('permisos.list_active'), 'mdi:lock') }}
        {% endif %}
        {% if current_user.can_view('USUARIOS') %}
            {{ topbar.button('Usuarios', url_for('usuarios.list_active'), 'mdi:account-key') }}
        {% endif %}
        {% if current_user.can_edit('ROLES') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('roles.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('roles.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('ROLES') %}
            {{ topbar.button_new('Nuevo Rol', url_for('roles.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <!-- Filtros roles -->
        <div class="row">
            <div class="col">
                <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosRoles.buscar(); return false;">
                    <div class="col-6">
                        <div class="form-floating">
                            <input id="filtroRolNombre" type="text" class="form-control" aria-label="Nombre" style="text-transform: uppercase;">
                            <label for="filtroRolNombre">Nombre</label>
                        </div>
                    </div>
                    <div class="col-6 text-end">
                        <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosRoles.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                        <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosRoles.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Datatable roles -->
        <table id="roles_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Roles</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    <script>
        // DataTable roles
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
        let configDataTable = constructorDataTable.config();
        configDataTable['ajax']['url'] = '/roles/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: 'detalle' }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.nombre + '</a>';
                }
            }
        ];
        // Filtros roles
        const filtrosRoles = new FiltrosDataTable('#roles_datatable', configDataTable);
        filtrosRoles.agregarInput('filtroRolNombre', 'nombre');
        filtrosRoles.precargar();
    </script>
{% endblock %}

plataforma_web/blueprints/roles/templates/roles/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Rol{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Rol') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('roles.new', fid='rol_form') %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}