plataforma_web/blueprints/tesis_jurisprudencias_sentencias/views.py
"""
Tesis uriesprudencias Sentencias, vistas
"""
import json
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_string, safe_message
from plataforma_web.blueprints.usuarios.decorators import permission_required

from plataforma_web.blueprints.bitacoras.models import Bitacora
from plataforma_web.blueprints.modulos.models import Modulo
from plataforma_web.blueprints.permisos.models import Permiso

from plataforma_web.blueprints.tesis_jurisprudencias.models import TesisJurisprudencia
from plataforma_web.blueprints.tesis_jurisprudencias_sentencias.models import TesisJurisprudenciaSentencia
from plataforma_web.blueprints.tesis_jurisprudencias_sentencias.forms import TesisSentenciaWithTesisForm

MODULO = "TESIS JURISPRUDENCIAS"

tesis_jurisprudencias_sentencias = Blueprint("tesis_jurisprudencias_sentencias", __name__, template_folder="templates")


@tesis_jurisprudencias_sentencias.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@tesis_jurisprudencias_sentencias.route("/tesis_jurisprudencias_sentencias/<int:tesis_jurisprudencia_sentencia_id>")
def detail(tesis_jurisprudencia_sentencia_id):
    """Detalle de una Tesis-Jurisprudencia Sentencias"""
    tesis_jurisprudencia_sentencia = TesisJurisprudenciaSentencia.query.get_or_404(tesis_jurisprudencia_sentencia_id)
    return render_template("tesis_jurisprudencias_sentencias/detail.jinja2", tesis_jurisprudencia_sentencia=tesis_jurisprudencia_sentencia)




@tesis_jurisprudencias_sentencias.route("/tesis_jurisprudencias_sentencias")
def list_active():
    """Listado de Sentencias de una Tesis o Jurisprudencia"""
    sentencias_activos = TesisJurisprudenciaSentencia.query.filter(TesisJurisprudenciaSentencia.estatus == "A").all()
    return render_template(
        "tesis_jurisprudencias_sentencias/list.jinja2",
        tesis_jurisprudencias_sentencias=sentencias_activos,
        titulo="Sentencias de una Tesis y Jurisprudencia",
        estatus="A",
    )

@tesis_jurisprudencias_sentencias.route("/tesis_jurisprudencias_sentencias/nuevo_con_tesis/<int:tesis_jurisprudencias_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new_with_tesis(tesis_jurisprudencias_id):
    """Nuevo Tesis-Sentencia con Tesis"""
    tesis_jurisprudencia = TesisJurisprudencia.query.get_or_404(tesis_jurisprudencias_id)
    form = TesisSentenciaWithTesisForm()
    if form.validate_on_submit():
        sentencia = form.sentencia.data
        descripcion = f"{sentencia.sentencia} en {tesis_jurisprudencia.clave_control} "
        if TesisJurisprudenciaSentencia.query.filter(TesisJurisprudenciaSentencia.tesis_jurisprudencia_id == tesis_jurisprudencias_id).filter(TesisJurisprudenciaSentencia.sentencia_id == sentencia.id).first() is not None:
            flash(f"CONFLICTO: Ya existe el Sentencia {descripcion}. Mejor recupere el registro.", "warning")
            return redirect(url_for("tesis_jurisprudencias_sentencias.list_inactive", tesis_jurisprudencias_id=tesis_jurisprudencias_id))
        tesis_sentencia= TesisJurisprudenciaSentencia(
            sentencia=sentencia,
            tesis_jurisprudencia=tesis_jurisprudencia,

        )
        tesis_sentencia.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Nueva sentencia en tesis-jurisprudencia-sentencia {tesis_sentencia.sentencia.sentencia}"),
            url=url_for("tesis_jurisprudencias_sentencias.detail", tesis_jurisprudencia_sentencia_id=tesis_sentencia.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    form.tesis.data = tesis_jurisprudencia.clave_control
    return render_template(
        "tesis_jurisprudencias_sentencias/new_with_tesis.jinja2",
        form=form,
        tesis_jurisprudencia=tesis_jurisprudencia,
        titulo=f"Agregar sentencia",
    )

@tesis_jurisprudencias_sentencias.route("/tesis_jurisprudencias_sentencias/inactivos/<int:tesis_jurisprudencias_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def list_inactive(tesis_jurisprudencias_id):
    """Listado de Tesis-Jurisprudencias-Sentencias inactivos"""
    tesis_sentencias_inactivos = TesisJurisprudenciaSentencia.query.filter(TesisJurisprudenciaSentencia.estatus == "B").filter(TesisJurisprudenciaSentencia.tesis_jurisprudencia_id == tesis_jurisprudencias_id).all()
    return render_template(
        "tesis_jurisprudencias_sentencias/list.jinja2",
        tesis_jurisprudencias_sentencias=tesis_sentencias_inactivos,
        titulo="Tesis-Jurisprudencias-Sentencias inactivos",
        estatus="B",
    )

@tesis_jurisprudencias_sentencias.route("/tesis_jurisprudencias_sentencias/eliminar/<int:tesis_jurisprudencia_sentencia_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def delete(tesis_jurisprudencia_sentencia_id):
    """Eliminar Tesis-Jurisprudencias-Sentencias"""
    tesis_sentencia = TesisJurisprudenciaSentencia.query.get_or_404(tesis_jurisprudencia_sentencia_id)
    if tesis_sentencia.estatus == "A":
        tesis_sentencia.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado tesis-jurisprudencia-sentencia {tesis_sentencia.sentencia.sentencia}"),
            url=url_for("tesis_jurisprudencias_sentencias.detail", tesis_jurisprudencia_sentencia_id=tesis_sentencia.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("tesis_jurisprudencias_sentencias.detail", tesis_jurisprudencia_sentencia_id=tesis_sentencia.id))

@tesis_jurisprudencias_sentencias.route("/tesis_jurisprudencias_sentencias/recuperar/<int:tesis_jurisprudencia_sentencia_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def recover(tesis_jurisprudencia_sentencia_id):
    """Tesis-Jurisprudencias-Sentencia"""
    tesis_sentencia = TesisJurisprudenciaSentencia.query.get_or_404(tesis_jurisprudencia_sentencia_id)
    if tesis_sentencia.estatus == "B":
        tesis_sentencia.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado tesis-jurisprudencias-funcionario {tesis_sentencia.sentencia.sentencia}"),
            url=url_for("tesis_jurisprudencias_sentencias.detail", tesis_jurisprudencia_sentencia_id=tesis_sentencia.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("tesis_jurisprudencias_sentencias.detail", tesis_jurisprudencia_sentencia_id=tesis_sentencia.id))

plataforma_web/blueprints/tesis_jurisprudencias_sentencias/templates/tesis_jurisprudencias_sentencias/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Tesis-Jurisprudencia-Sentencia{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Tesis-Jurisprudencia-Sentencias ' + tesis_jurisprudencia_sentencia.sentencia.sentencia + ', Expediente: ' +  tesis_jurisprudencia_sentencia.sentencia.expediente) %}
            {{ topbar.button_previous('Tesis-Jurisprudencias-Sentencias', url_for('tesis_jurisprudencias_sentencias.list_active')) }}
            {% if current_user.can_edit('TESIS JURISPRUDENCIAS') %}
                {% if tesis_jurisprudencia_sentencia.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('tesis_jurisprudencias_sentencias.delete', tesis_jurisprudencia_sentencia_id=tesis_jurisprudencia_sentencia.id)) }}{% endif %}
                {% if tesis_jurisprudencia_sentencia.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('tesis_jurisprudencias_sentencias.recover', tesis_jurisprudencia_sentencia_id=tesis_jurisprudencia_sentencia.id)) }}{% endif %}
            {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=tesis_jurisprudencia_sentencia.estatus) %}
        {{ detail.label_value('Sentencia', tesis_jurisprudencia_sentencia.sentencia.sentencia + ' ' +  tesis_jurisprudencia_sentencia.sentencia.expediente, url_for('sentencias.detail', sentencia_id=tesis_jurisprudencia_sentencia.sentencia.id)) }}
        {{ detail.label_value('Tesis y jurisprudencias', tesis_jurisprudencia_sentencia.tesis_jurisprudencia.clave_control, url_for('tesis_jurisprudencias.detail', tesis_jurisprudencia_id=tesis_jurisprudencia_sentencia.tesis_jurisprudencia_id)) }}
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_edit('TESIS JURISPRUDENCIAS') %}
        {% if tesis_jurisprudencia_sentencia.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + tesis_jurisprudencia_sentencia.sentencia.sentencia + '?') }}{% endif %}
        {% if tesis_jurisprudencia_sentencia.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + tesis_jurisprudencia_sentencia.sentencia.sentencia + '?') }}{% endif %}
    {% endif %}
{% endblock %}

plataforma_web/blueprints/tesis_jurisprudencias_sentencias/templates/tesis_jurisprudencias_sentencias/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Sentencias{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('SENTENCIAS') %}
            {{ topbar.button('Sentencias', url_for('sentencias.list_active'), 'mdi:gamepad') }}
        {% endif %}
        {% if current_user.can_view('TESIS JURISPRUDENCIAS') %}
            {{ topbar.button('TesisJurisprudencias', url_for('tesis_jurisprudencias.list_active'), 'mdi:gavel') }}
        {% endif %}
        {% if current_user.can_edit('TESIS JURISPRUDENCIAS SENTENCIAS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('tesis_jurisprudencias_sentencias.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('tesis_jurisprudencias_sentencias.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('TESIS JURISPRUDENCIAS SENTENCIAS') %}
            {{ topbar.button_new('Nuevo Tesis-Jurisprudencia-Sentencia', url_for('tesis_jurisprudencias_sentencias.new_with_tesis')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <table id="tesis_jurisprudencias_sentencias_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Tesis y Jurisprudencia</th>
                    <th>Sentencia</th>
                </tr>
            </thead>
            <tbody>
                {% for tesis_sentencia in tesis_jurisprudencias_sentencias %}
                <tr>
                    <td>{{ tesis_sentencia.tesis_jurisprudencia.clave_control  }}</td>
                    <td><a href="{{ url_for('tesis_jurisprudencias_sentencias.detail', tesis_jurisprudencia_sentencia_id=tesis_sentencia.id) }}">{{ tesis_sentencia.sentencia.sentencia }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ list.datatable('tesis_jurisprudencias_sentencias_datatable') }}
{% endblock %}

plataforma_web/blueprints/tesis_jurisprudencias_sentencias/templates/tesis_jurisprudencias_sentencias/new_with_tesis.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Agregar sentencias a la tesis y Jurisprudencia{% endblock %}

{% block topbar_actions %}
    {{ topbar.page(titulo) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'tesis_jurisprudencias_id': tesis_jurisprudencia.id} %}
        {% call f.form_tag('tesis_jurisprudencias_sentencias.new_with_tesis', fid='tesis_jurisprudencia_sentencia_form', **form_kwargs) %}
            {% call f.form_group(form.sentencia) %}{% endcall %}
            {% call f.form_group(form.tesis, readonly=true) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}